### ISSUE TITLE
[Solved] Error: manifest path..

### ISSUE THREAD

**Issue by naguam** [perceptia/perceptia#13]
Hello I'm new here and maybe in the future, I will do contributions.

I'm going to describe what I do for helping you to help me :)

So I'm using debian testing i386 (9 stretch) on my eeepc with unstable and experimental repositories with pinning.

My eeepc works with wayland I tested with sway but I want to try perceptia :)

So I installed your dependencies :  

`apt -t unstable install cargo ` (it makes rustc installing with it)
The version of cargo installed is 0-17-0  (unstable package) and the rustc one is 1.14.0 (testing package)  (versions said with  `cargo -V` and `rustc -V`)

Then I installed your dependencies (versions said with apt search)

libdbus = `libdbus-1-dev`   (v 1.10.18)
libdrm = `libdrm2` and `libdrm-dev`   (v 2.4.74 for the two)
libgbm = `libgbm1` and `libgbm-dev`   (v 13.0.6 for the two)
libgl = `libgles2-mesa-dev`   (v 13.0.6)
libegl = `libegl1-mesa-dev`   (v 13.0.6)
libudev = `libudev1` and `libudev-dev`   (v 232 for the two)
libxkbcommon = `libxkbcommon0` and `libxkbcommon-dev`   (v 0.7.1 for the two)

I saw `libxkbcommon-x11` and `libxkbcommon-x11-dev` but perceptia uses wayland, and sway didn't use those two packages so I thought that we have not to install them.

Maybe it was not necessary to install libsystemd-dev but i installed it too
I installed xwayland and wayland-protocols too.

Then I used [your official tutorial](https://github.com/perceptia/perceptia/blob/master/info/installation.md) and i download by doing `git clone https://github.com/perceptia/perceptia.git`, and then, now, I have an error when I'm in `src/` and doing `cargo build` (I used cargo one time already but I'm a "beginner" in cargo (and in many things ))

The error is: 

> error: manifest path `/root/perceptia/Cargo.toml` is a virtual manifest, but this command running against an actual package in this workspace

So then, what is the problem? :)

Sorry if I have a bad English, I'm French ;)  

I hope I tell you enought infos to help me :)

ps: Have you got some screenshots?

**Comment by darkelement** [comment]
Thank you for trying `perceptia`!

 - To build only `perceptia` go to `src/perceptia` and then `cargo build --release`.
 - To build everything stay in repo root and run `cargo build --release --all`.

Binaries will land in `target/release/`. Press `[ctrl]+[meta]+T` to run terminal. You probably saw https://github.com/perceptia/perceptia/blob/master/info/configuration.md I will update docs today to make them more clear.

There are packages for Arch Linux on AUR if you are interested. I will also probably make debs available with next release.

Xwayland is not supported yet. I'm implementing everything from scratch in Rust. If you need that, fill an issue. This will help me to decide what should be implemented first.

If you want to contribute then it's more handy to use `rustup`. It allows to easily update rustc and switch between release channels. There are couple of relatively simple issues for beginners in bugtracker.

Screenshots are on wiki: https://github.com/perceptia/perceptia/wiki/Screenshots (I will add more today.)

**Comment by darkelement** [comment]
Not finished, but updated version will look like:

https://github.com/perceptia/perceptia/blob/wip_environment/info/installation.md

**Comment by naguam** [comment]
I'm glad to use perceptia.
But I will change my test machine because of some other thing I have to try on the eeepc so I will usr a dell latitude with debian sid amd64

I don't understand what `--all` do (root repo.. git..)
Can you explain? :)
But I will try your commands! :)

I like Archlinux only for the Aur and the fact It is a rolling and i use it for some kind of machine, but I wnat to install perceptia with debian, debian sid is a rolling and flexible because it works on many architecture.
But thanks to inform me :)

Yes I think I will fill an issue for Xwayland because some of the programms I need don't support wayland for now.
But all writing from scratch with rust is great ;)

What terminal emulator do you use on your screen, the weston one?

Maybe I will contribute but before I habe to read all your infos about that and I'm a beginner in programming and coding.
I will inform myself about `rustup` :)

Thank for the new `installation.md` :)

I'm not to active because now i have not many time so don't think I abandoned the project :) (I's just an info)

**Comment by naguam** [comment]
I'm glad to use perceptia.
But I will change my test machine because of some other thing I have to try on the eeepc so I will usr a dell latitude with debian sid amd64

I don't understand what `--all` do (root repo.. git..)
Can you explain? :)
But I will try your commands! :)

I like Archlinux only for the Aur and the fact It is a rolling and i use it for some kind of machine, but I wnat to install perceptia with debian, debian sid is a rolling and flexible because it works on many architecture.
But thanks to inform me :)

Yes I think I will fill an issue for Xwayland because some of the programms I need don't support wayland for now.
But all writing from scratch with rust is great ;)

What terminal emulator do you use on your screen, the weston one?

Maybe I will contribute but before I habe to read all your infos about that and I'm a beginner in programming and coding.
I will inform myself about `rustup` :)

Thank for the new `installation.md` :)

I'm not to active because now i have not many time so don't think I abandoned the project :) (I's just an info)

**Comment by naguam** [comment]
So I tryed on my dell latitude using debian sid. Have we again to be in `src` because I try in it and I've got errors when I try in it.
Now I will try in the `preceptia` repository but not in `src`.

**Comment by naguam** [comment]
So I tried only `cargo build`(only) and same error as on the eeepc,

So I will let you the error with your command just in few minutes.

**Comment by naguam** [comment]
So this is the error ([URL ---> Pastebin]( https://pastebin.com/4m2BCDQb)) (I didn't understand why cargo compile a gcc version while I have gcc 6, but I think It's about to have less dependencies to install, my conclusion : cargo compile all the dependencies we need to build but not to launch)

**Comment by darkelement** [comment]
You have old version of rustc (1.16.0?). I made fix to compile with that version. You can now pull the changes (or if you are not familiar with git, download the repo again).

**Comment by naguam** [comment]
At the beginning, on the eeepc, the rustc package was 1.14.0 and now on unstable It's 1.16.0 yes.
The packages I listed at the beginning have some versions newer than testings ones but not the lastest for all.
I know the bases of git so I can `pull` `clone` etc but I'm not the best a it :p 
Thank you for your fix the `cargo build --all --release` works but now, have I to `cargo install`? or it's already done?    
Do the fix work too for newer rustc version? (I think yes but I'm not sure)

**Comment by darkelement** [comment]
What would you need `cargo install` for? You can execute application with `./path/to/application`.

**Comment by naguam** [comment]
Ok ok, I'm gonna learn cargo and try :)

**Comment by naguam** [comment]
[I tryed to launch and that link is the log](https://pastebin.com/iRm2HDAa)

**Comment by naguam** [comment]
I see it's works, I've a blue screen with en white square in the middle, I'm gonna to learn the configuration with your guide but I've a question, is it possible to install it in /usr/local or /opt, because keeping the files in the /home/user ...   I ask that but I think the configuration in user will stay in /home/user/.. etc.

Then I continue to read but I think I will not continue too much because of life obligations but I continue to follow the project (and to test it under debian but I will try arch and gentoo (for some news ideas))

Maybe, I might create an issue for xwayland but i'ts not sure, but xwayland is important for me because of some apps.

I admire you because of writing from scratch.

ps: I will try to add it in an entry of lightdm but I don't know how (but don't explain it to me here it's because off the issue, but now it is solved)

**Comment by darkelement** [comment]
That's great it works. I'm curious about your hardware, could you post output of `perceptiactl info` command?

Sure it can be installed anywhere. Just don't do that manually. People invented `deb`s, `rpm`s and others for a reason. I will prepare `deb` soon. Just didn't have time so far.

Good luck with your "life things".
